services:
  opendaylight:
    image: opendaylight/odl:latest
    ports:
      - "8181:8181" # RESTCONF
      - "6633:6633" # OpenFlow
    environment:
      - ODL_INSTALL_FEATURES=odl-restconf,odl-l2switch-switch,odl-mdsal-apidocs,odl-dlux-core

  sdn-adapter:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      - ODL_URL=http://opendaylight:8181
    depends_on:
      - opendaylight

  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_SDN_ADAPTER_URL=http://localhost:4000
    depends_on:
      - sdn-adapter
