apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "axiom-topology.fullname" . }}-frontend
  labels:
    {{- include "axiom-topology.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "axiom-topology.frontendSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "axiom-topology.frontendSelectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.service.targetPort }}
              name: http
          env:
            - name: SDN_ADAPTER_HOSTPORT
              value: {{ .Values.frontend.env.SDN_ADAPTER_HOSTPORT | quote }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
