apiVersion: v1
kind: Secret
metadata:
  name: {{ include "axiom-topology.fullname" . }}-secret
  labels:
    {{- include "axiom-topology.labels" . | nindent 4 }}
type: Opaque
data:
  ODL_PASSWORD: {{ .Values.secrets.ODL_PASSWORD | b64enc | quote }}
  API_TOKEN: {{ .Values.secrets.API_TOKEN | b64enc | quote }}
