apiVersion: v1
kind: Service
metadata:
  name: {{ include "axiom-topology.fullname" . }}-frontend
  labels:
    {{- include "axiom-topology.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    {{- include "axiom-topology.frontendSelectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      name: http
